# Generated by Django 4.2.6 on 2023-10-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateField()),
                ('call_status', models.CharField(max_length=100)),
                ('contact_type', models.CharField(max_length=100)),
                ('demo_status', models.CharField(max_length=100)),
                ('demo_note', models.CharField(max_length=255)),
                ('call_note', models.CharField(max_length=255)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('interaction_type', models.CharField(max_length=20)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
