# Generated by Django 4.2.6 on 2023-11-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='employee',
        ),
    ]
